baseURL = "https://humane.house"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Humane ğŸ‘ªâ¤ï¸ğŸ  House"
theme = "anubis"
paginate = 3
enableEmoji = true
publishDir = ".dist"

disqusShortname = ""
googleAnalytics = ""

[params]
description = "Let's build a better housing market, together."
images = ['images/social/cover.png']
title = "Humane ğŸ‘ªâ¤ï¸ğŸ  House"
dateFormat = "2006-01-02"
paginationSinglePost = true
style = "light-without-switcher"
readMore = false

# utteranc.es support
utterancesRepo = ""  # mandatory
utterancesTheme = "" # optional
utterancesIssue = "" # optional
utterancesLabel = "" # optional

#[[params.social]]
#id = "docs"
#url = "https://gohugo.io/documentation/"

[languages.en]
languageName = "English"

#[[menu.main]]
#identifier = "about"
#name = "About"
#url = "/about/"
#weight = 1

#[[menu.main]]
#identifier = "tags"
#name = "Tags"
#url = "/tags/"
#weight = 2

#[[menu.main]]
#name = "Archive"
#identifier = "archive"
#url = "/posts/"
#weight = 3

#[languages.pl]
#languageName = "Polski"

#[[languages.pl.menu.main]]
#identifier = "about"
#name = "O Hugo"
#url = "/about/"
#weight = 1

#[[languages.pl.menu.main]]
#identifier = "tags"
#name = "Tagi"
#url = "/tags/"
#weight = 2

#[[languages.pl.menu.main]]
#identifier = "archive"
#name = "Archiwum"
#url = "/posts/"
#weight = 3

[taxonomies]
category = "categories"
tag = "tags"

[markup.goldmark.renderer]
unsafe = true